### ISSUE TITLE
Better integration with other dialects

### ISSUE THREAD

**Issue by martin-luecke** [rise-lang/mlir#1]
Currently integration with other MLIR dialects is restricted to calling a function with RISE code from anywhere and using the result.
We want to support the mixing of arbitrary dialects with RISE. This way the advantages of having a lambda calculus representation in MLIR will be available to all abstraction levels. 

As the current type system is very restrictive in this matter, these restrictions will have to be loosened a bit. Instead of operating on our own `rise.int` and `rise.float` we will introduce `rise.scalar`, which wraps an arbitrary scalar type. 
We will also drop the operations `rise.add` and `rise.mult`. They will be replaced by using the existing operations in MLIR e.g. `std.addf`. 
As operations of other dialects (like `std.addf`) don't operate on RISE types we will bridge (cast) arguments and results using the new operations `rise.unwrap` and `rise.wrap`. 
A simple example showing how this change changes our running example of doubling all values in an array.
```C++
    rise.fun "rise_fun" (%outArg:memref<4xf32>, %in:memref<4xf32>) {
        %array = rise.in %in : !rise.data<array<4, float>>
        %doubleFun = rise.lambda (%summand) : !rise.fun<data<float> -> data<float>> {
            %addFun = rise.add #rise.float
            %doubled = rise.apply %addFun, %summand, %summand
            rise.return %doubled : !rise.data<float>
        }
        %mapFun = rise.map #rise.nat<4> #rise.float #rise.float
        %doubledArray = rise.apply %mapFun, %doubleFun, %array

        rise.return %doubledArray : !rise.data<array<4, float>>
    }
```
turns into: (not final printing form)
```C++
    rise.fun "rise_fun" (%outArg:memref<4xf32>, %in:memref<4xf32>) {
        %array = rise.in %in : !rise.array<4, scalar<f32>>
        %doubleFun = rise.lambda (%summand) : !rise.fun<scalar<f32> -> scalar<f32>> {
            %summandUnwrapped = rise.unwrap %summand
            %doubled = addf %summandUnwrapped, %summandUnwrapped    // This section can contain arbitrary operations using the %summandUnwrapped. This is opaque to RISE 
            %doubledWrapped = rise.wrap %doubled
            return %doubledWrapped : !rise.scalar<f32>
        }
        %mapFun = rise.map #rise.nat<4> #rise.scalar<f32> #rise.scalar<f32>
        %doubledArray = rise.apply %mapFun, %doubleFun, %array

        return %doubledArray : !rise.array<4, scalar<f32>>
    }
```
In consequence the section between `rise.unwrap %arg` and `rise.wrap %result` may contain arbitrary operations from different dialects. These are opaque to RISE and will be preserved in the lowering to imperative. 

This approach will enable performing lambda calculus rewriting even when RISE is mixed with outher dialects.

#### Summary:
- remove types `rise.int`, `rise.float`
- introduce type `rise.scalar`
- remove operations `rise.add`, `rise.mult`
- introduce operations `rise.unwrap`, `rise.wrap`

Long example of dot in this form:

```C++
rise.fun "rise_fun" (%outArg:memref<4xf32>) {
  //Arrays
  %array0 = rise.literal #rise.lit<array<4, !rise.scalar<f32>, [5,5,5,5]>>
  %array1 = rise.literal #rise.lit<array<4, !rise.scalar<f32>, [5,5,5,5]>>
  //Zipping
  %zipFun = rise.zip #rise.nat<4> #rise.scalar<float> #rise.scalar<float>
  %zippedArrays = rise.apply %zipFun, %array0, %array1
  //Multiply
  %tupleMulFun = rise.lambda (%floatTuple) : !rise.fun<tuple<scalar<float>, scalar<float>> -> scalar<float>> {
    %fstFun = rise.fst #rise.scalar<float> #rise.scalar<float>
    %sndFun = rise.snd #rise.scalar<float> #rise.scalar<float>
    %fst = rise.apply %fstFun, %floatTuple
    %snd = rise.apply %sndFun, %floatTuple
    %fst_unwrapped = rise.unwrap %fst  // () -> rise.scalar<float> -> float
    %snd_unwrapped = rise.unwrap %snd
    %result_unwrapped = addf %fsd_unwrapped %snd_unwrapped
    %result = rise.wrap %result_unwrapped
    return %result : !rise.scalar<float>
  }
  %map10TuplesToInts = rise.map #rise.nat<4> #rise.tuple<float, float> #rise.float
  %multipliedArray = rise.apply %map10TuplesToInts, %tupleMulFun, %zippedArrays
  //Reduction
  %reductionAdd = rise.lambda (%summand0, %summand1) : !rise.fun<scalar<f32> -> fun<scalar<f32> -> scalar<f32>>> {
    %summand0_unwrapped = rise.unwrap %summand0
    %summand1_unwrapped = rise.unwrap %summand1
    %doubled = addf %summand0_unwrapped %summand1_unwrapped
    %doubled_wrapped = rise.wrap %doubled
    return %doubled_wrapped : !rise.scalar<f32>
  }
  %initializer = rise.literal #rise.lit<0>
  %reduceFun = rise.reduce #rise.nat<4> #rise.scalar<f32> #rise.scalar<f32>
  %result = rise.apply %reduceFun, %reductionAdd, %initializer, %multipliedArray
  return %result : !rise.scalar<f32>
}
```

**Comment by rengolin** [comment]
This makes a lot more sense to me than trying to replicate every basic operation. It also allows calling functions as operations, so that we can define composable logic from other dialects (including standard) as part of the lambdas.

In that sense, #2 seems redundant. What's your time scale in implementing these changes?

**Comment by martin-luecke** [comment]
I agree, this will also allow using our lambda calculus representation at different levels of abstraction and do (at some point) rewriting on them.

I will work on this from today and during the next week. I expect this will be ready for experimentation next week.

**Comment by rengolin** [comment]
Awesome! I'll cancel #2, then. Thanks!

**Comment by martin-luecke** [comment]
The proposal is implemented in the branch [feature/relaxedTypesystem](https://github.com/rise-lang/mlir/compare/feature/relaxedTypesystem). 
Lowering works for all [examples](https://github.com/rise-lang/mlir/tree/feature/relaxedTypesystem/mlir/test/Conversion/RiseToImperative) I have.

We are currently writing up a paper about this until the 24th. I probably won't have time until then to polish the implementation and do a PR. I suggest you check out this branch and see if this makes sense. 

I am looking forward to any questions you have.

**Comment by rengolin** [comment]
I don't have specific comments on the patch itself, but I've been working on my own dialect and I have more or less done in the same way. Types and basic constructs (like functions or calls) I'm using from Std, and just defining specific types like DataType, TupleType, etc. as well as some syntactic sugar of our IR.

Overall, I think that's a better way to handle MLIR, as it will likely require less conversions to Rise from other formats (TF, ONNX). The downside will probably be that the rules or the traversal won't be as effective as possible, but that's still "more effective" than not converting the whole graph and missing out on a large search space.

I'll continue working on my side and hopefully when I have something more concrete, I can do another, more thorough review of the code. Hopefully by then you'd also have more concrete examples. :)

**Comment by martin-luecke** [comment]
See #5
